# Task 27 composes all platform modules. Dependencies are expressed through
# module outputs; root-owned policies below break the IAM/ECS and S3/CloudFront
# cycles called out in the design.
data "aws_partition" "current" {}
data "aws_caller_identity" "current" {}
module "network" {
  source = "../../modules/network"

  name_prefix                     = local.name_prefix
  common_tags                     = local.common_tags
  vpc_cidr                        = var.network_vpc_cidr
  availability_zones              = var.network_availability_zones
  public_subnet_cidrs             = var.network_public_subnet_cidrs
  private_app_subnet_cidrs        = var.network_private_app_subnet_cidrs
  isolated_db_subnet_cidrs        = var.network_isolated_db_subnet_cidrs
  enable_nat_gateway              = var.network_enable_nat_gateway
  allowed_alb_ingress_cidrs       = var.network_allowed_alb_ingress_cidrs
  app_port                        = var.network_app_port
  external_https_egress_cidrs     = var.network_external_https_egress_cidrs
  enable_vpc_endpoints            = var.network_enable_vpc_endpoints
  interface_vpc_endpoint_services = var.network_interface_vpc_endpoint_services
}

module "ecr" {
  source = "../../modules/ecr"

  name_prefix                    = local.name_prefix
  common_tags                    = local.common_tags
  image_tag_mutability           = var.ecr_image_tag_mutability
  untagged_image_expiration_days = var.ecr_untagged_image_expiration_days
  tagged_image_retention_count   = var.ecr_tagged_image_retention_count
  retained_tag_prefixes          = var.ecr_retained_tag_prefixes
}

# Task 6.1 consumes the network module's isolated DB subnet and DB security
# group outputs. These references establish the network-to-Aurora dependency;
# never replace them with public or private application subnets.
module "aurora" {
  source = "../../modules/aurora"

  name_prefix                     = local.name_prefix
  common_tags                     = local.common_tags
  database_subnet_ids             = values(module.network.isolated_db_subnet_ids)
  db_security_group_id            = module.network.security_group_ids.db
  database_name                   = var.aurora_database_name
  engine_version                  = var.aurora_engine_version
  master_username                 = var.aurora_master_username
  master_user_secret_kms_key_id   = var.aurora_master_user_secret_kms_key_id
  min_capacity                    = var.aurora_min_capacity
  max_capacity                    = var.aurora_max_capacity
  backup_retention_period         = var.aurora_backup_retention_period
  enabled_cloudwatch_logs_exports = var.aurora_enabled_cloudwatch_logs_exports
  performance_insights_enabled    = var.aurora_performance_insights_enabled
  deletion_protection             = var.aurora_deletion_protection
  skip_final_snapshot             = var.aurora_skip_final_snapshot
  final_snapshot_identifier       = var.aurora_final_snapshot_identifier
}

# CodePipeline, CodeBuild, artifact storage, and execution IAM roles are owned
# only by bootstrap/. The canonical dev pipeline contract is documented in
# pipeline-contract.md; this root owns backend inputs and module wiring only.

# --------------------------------------------------------------------------- #
# Task 3: Backend internal bearer token secret (dev root single owner).
#
# The token is generated by random_password and stored only in Secrets Manager.
# The real value is NOT exposed via any Terraform output, log, plaintext
# environment variable, tfvars, or README. Only the secret ARN is passed to the
# IAM and ECS modules. The generated value may reside in Terraform state, which
# is protected by the encrypted, access-restricted, versioned remote state
# (Req 4.2, 27.3).
# --------------------------------------------------------------------------- #
resource "random_password" "backend_bearer" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "backend_bearer" {
  name                    = "${local.name_prefix}-backend-internal-bearer"
  description             = "Backend_API internal bearer token (BACKEND_INTERNAL_BEARER_TOKEN). Value managed by Terraform; never output in plaintext."
  recovery_window_in_days = var.backend_bearer_secret_recovery_window_days

  tags = merge(local.common_tags, {
    Name = "${local.name_prefix}-backend-internal-bearer"
    Role = "backend-internal-bearer"
  })
}

resource "aws_secretsmanager_secret_version" "backend_bearer" {
  secret_id     = aws_secretsmanager_secret.backend_bearer.id
  secret_string = random_password.backend_bearer.result
}

module "messaging" {
  source = "../../modules/messaging"

  name_prefix = local.name_prefix
  common_tags = local.common_tags
}

module "dynamodb" {
  source = "../../modules/dynamodb"

  name_prefix = local.name_prefix
  common_tags = local.common_tags
}

module "s3_portal" {
  source = "../../modules/s3-portal"

  name_prefix   = local.name_prefix
  common_tags   = local.common_tags
  aws_region    = var.aws_region
  force_destroy = var.portal_bucket_force_destroy
}

module "logging" {
  source = "../../modules/logging"

  name_prefix = local.name_prefix
  common_tags = local.common_tags
  vpc_id      = module.network.vpc_id
}

module "iam" {
  source = "../../modules/iam"

  name_prefix = local.name_prefix
  common_tags = local.common_tags
  aws_region  = var.aws_region

  backend_ecr_repository_arn   = module.ecr.repository_arns["backend-api"]
  migration_ecr_repository_arn = module.ecr.repository_arns["db-migration"]
  backend_bearer_secret_arn    = aws_secretsmanager_secret.backend_bearer.arn
  db_secret_arn                = module.aurora.app_database_secret_arn

  migration_launcher_trusted_principal_arns = var.migration_launcher_trusted_principal_arns
}

# ALB log storage is a root-owned glue resource because its globally unique
# name needs the current account/region while the ALB module consumes the name.
resource "aws_s3_bucket" "alb_access_logs" {
  bucket        = local.alb_access_logs_bucket
  force_destroy = var.alb_access_logs_force_destroy

  tags = merge(local.common_tags, {
    Name = local.alb_access_logs_bucket
    Role = "alb-access-logs"
  })
}

resource "aws_s3_bucket_ownership_controls" "alb_access_logs" {
  bucket = aws_s3_bucket.alb_access_logs.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

resource "aws_s3_bucket_public_access_block" "alb_access_logs" {
  bucket = aws_s3_bucket.alb_access_logs.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "alb_access_logs" {
  bucket = aws_s3_bucket.alb_access_logs.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "alb_access_logs" {
  bucket = aws_s3_bucket.alb_access_logs.id

  rule {
    id     = "expire-alb-access-logs"
    status = "Enabled"

    filter {}

    expiration {
      days = var.alb_access_logs_expiration_days
    }
  }
}

data "aws_iam_policy_document" "alb_access_logs" {
  statement {
    sid       = "AllowLogDeliveryBucketCheck"
    effect    = "Allow"
    actions   = ["s3:GetBucketAcl"]
    resources = [aws_s3_bucket.alb_access_logs.arn]

    principals {
      type        = "Service"
      identifiers = ["logdelivery.elasticloadbalancing.amazonaws.com"]
    }
  }

  statement {
    sid       = "AllowLogDeliveryWrite"
    effect    = "Allow"
    actions   = ["s3:PutObject"]
    resources = ["${aws_s3_bucket.alb_access_logs.arn}/${var.alb_access_logs_prefix}/AWSLogs/${data.aws_caller_identity.current.account_id}/*"]

    principals {
      type        = "Service"
      identifiers = ["logdelivery.elasticloadbalancing.amazonaws.com"]
    }
  }
}

resource "aws_s3_bucket_policy" "alb_access_logs" {
  bucket = aws_s3_bucket.alb_access_logs.id
  policy = data.aws_iam_policy_document.alb_access_logs.json
}

module "alb" {
  source = "../../modules/alb"

  name_prefix           = local.name_prefix
  common_tags           = local.common_tags
  vpc_id                = module.network.vpc_id
  public_subnet_ids     = values(module.network.public_subnet_ids)
  allowed_ingress_cidrs = var.network_allowed_alb_ingress_cidrs
  create_security_group = false
  alb_security_group_id = module.network.security_group_ids.alb
  ecs_security_group_id = module.network.security_group_ids.ecs
  app_port              = var.network_app_port
  certificate_arn       = var.alb_certificate_arn
  access_logs_bucket    = aws_s3_bucket.alb_access_logs.bucket
  access_logs_prefix    = var.alb_access_logs_prefix

  depends_on = [aws_s3_bucket_policy.alb_access_logs]
}

module "ecs" {
  source = "../../modules/ecs"

  name_prefix           = local.name_prefix
  common_tags           = local.common_tags
  private_subnet_ids    = values(module.network.private_app_subnet_ids)
  ecs_security_group_id = module.network.security_group_ids.ecs
  target_group_arn      = module.alb.target_group_arn

  backend_execution_role_arn   = module.iam.backend_execution_role_arn
  backend_task_role_arn        = module.iam.backend_task_role_arn
  migration_execution_role_arn = module.iam.migration_execution_role_arn
  migration_task_role_arn      = module.iam.migration_task_role_arn

  container_image           = local.application_images.backend
  migration_container_image = local.application_images.migration
  backend_db_secret_arn     = module.aurora.app_database_secret_arn
  backend_db_name           = module.aurora.database_name
  backend_bearer_secret_arn = aws_secretsmanager_secret.backend_bearer.arn
  app_port                  = var.network_app_port
  ecs_desired_count         = var.ecs_desired_count
  aws_region                = var.aws_region
}

module "eks" {
  source = "../../modules/eks"

  name_prefix                   = local.name_prefix
  common_tags                   = local.common_tags
  eks_kubernetes_version        = var.eks_kubernetes_version
  private_subnet_ids            = values(module.network.private_app_subnet_ids)
  eks_security_group_id         = module.network.security_group_ids.eks
  db_secret_arn                 = module.aurora.app_database_secret_arn
  alarm_queue_arn               = module.messaging.alarm_queue_arn
  finding_queue_arn             = module.messaging.finding_queue_arn
  eks_public_access_cidrs       = var.eks_public_access_cidrs
  eks_operator_principal_arn    = var.eks_operator_principal_arn
  portal_reports_bucket_arn     = module.s3_portal.bucket_arn
  report_metadata_table_arn     = module.dynamodb.report_metadata_table_arn
  public_status_items_table_arn = module.dynamodb.public_status_items_table_arn
}

resource "aws_eks_access_entry" "operator" {
  cluster_name  = module.eks.cluster_name
  principal_arn = var.eks_operator_principal_arn
  type          = "STANDARD"
  tags          = local.common_tags

  depends_on = [module.eks]
}

resource "aws_eks_access_policy_association" "operator" {
  cluster_name  = module.eks.cluster_name
  principal_arn = aws_eks_access_entry.operator.principal_arn
  policy_arn    = "arn:${data.aws_partition.current.partition}:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"

  access_scope {
    type = "cluster"
  }
}

module "waf" {
  source = "../../modules/waf"

  providers = {
    aws = aws.us_east_1
  }

  name_prefix                        = local.name_prefix
  common_tags                        = local.common_tags
  waf_additional_managed_rule_groups = var.waf_additional_managed_rule_groups
  waf_logging_enabled                = var.waf_logging_enabled
  waf_kms_enabled                    = var.waf_kms_enabled
  waf_log_retention_days             = var.waf_log_retention_days
}

module "lambda" {
  source = "../../modules/lambda"

  name_prefix = local.name_prefix
  common_tags = local.common_tags

  lambda_package_s3_bucket         = var.lambda_package_s3_bucket
  lambda_package_s3_key            = var.lambda_package_s3_key
  lambda_package_s3_object_version = var.lambda_package_s3_object_version
  lambda_source_code_hash          = var.lambda_source_code_hash

  public_status_items_table_arn = module.dynamodb.public_status_items_table_arn
  report_metadata_table_arn     = module.dynamodb.report_metadata_table_arn
  maintenance_windows_table_arn = module.dynamodb.maintenance_windows_table_arn
  page_view_logs_table_arn      = module.dynamodb.page_view_logs_table_arn
}

module "cognito" {
  source = "../../modules/cognito"

  name_prefix                 = local.name_prefix
  common_tags                 = local.common_tags
  aws_region                  = var.aws_region
  cognito_callback_urls       = var.cognito_callback_urls
  cognito_logout_urls         = var.cognito_logout_urls
  cognito_keep_localhost_urls = var.cognito_keep_localhost_urls
}

module "apigateway" {
  source = "../../modules/apigateway"

  name_prefix          = local.name_prefix
  common_tags          = local.common_tags
  jwt_issuer_url       = module.cognito.issuer_url
  jwt_audiences        = [module.cognito.app_client_id]
  lambda_invoke_arn    = module.lambda.lambda_invoke_arn
  lambda_function_name = module.lambda.lambda_function_name
}

module "cloudfront" {
  source = "../../modules/cloudfront"

  name_prefix               = local.name_prefix
  common_tags               = local.common_tags
  s3_origin_domain_name     = module.s3_portal.bucket_regional_domain_name
  api_gateway_origin_domain = module.apigateway.api_domain_name
  web_acl_arn               = module.waf.web_acl_arn
  price_class               = var.cloudfront_price_class
}

data "aws_iam_policy_document" "portal_oac" {
  statement {
    sid       = "AllowCloudFrontReadOnly"
    effect    = "Allow"
    actions   = ["s3:GetObject"]
    resources = ["${module.s3_portal.bucket_arn}/*"]

    principals {
      type        = "Service"
      identifiers = ["cloudfront.amazonaws.com"]
    }

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceArn"
      values   = [module.cloudfront.distribution_arn]
    }
  }
}

resource "aws_s3_bucket_policy" "portal_oac" {
  bucket = module.s3_portal.bucket_name
  policy = data.aws_iam_policy_document.portal_oac.json
}

data "aws_iam_policy_document" "migration_launcher" {
  statement {
    sid       = "RunMigrationTask"
    effect    = "Allow"
    actions   = ["ecs:RunTask"]
    resources = [module.ecs.migration_task_definition_arn]

    condition {
      test     = "ArnEquals"
      variable = "ecs:cluster"
      values   = [module.ecs.migration_cluster_arn]
    }
  }

  statement {
    sid       = "DescribeMigrationTask"
    effect    = "Allow"
    actions   = ["ecs:DescribeTasks"]
    resources = ["*"]

    condition {
      test     = "StringEquals"
      variable = "aws:RequestedRegion"
      values   = [var.aws_region]
    }
  }

  statement {
    sid     = "PassMigrationRoles"
    effect  = "Allow"
    actions = ["iam:PassRole"]
    resources = [
      module.iam.migration_execution_role_arn,
      module.iam.migration_task_role_arn,
    ]

    condition {
      test     = "StringEquals"
      variable = "iam:PassedToService"
      values   = ["ecs-tasks.amazonaws.com"]
    }
  }
}

resource "aws_iam_role_policy" "migration_launcher" {
  name   = "${local.name_prefix}-migration-launcher-policy"
  role   = module.iam.migration_launcher_role_name
  policy = data.aws_iam_policy_document.migration_launcher.json
}

module "monitoring" {
  source = "../../modules/monitoring"

  name_prefix = local.name_prefix
  common_tags = local.common_tags
  aws_region  = var.aws_region

  alarm_dlq_queue_name         = module.messaging.alarm_dlq_name
  finding_dlq_queue_name       = module.messaging.finding_dlq_name
  ecs_cluster_name             = module.ecs.cluster_name
  ecs_service_name             = module.ecs.service_name
  eks_cluster_name             = module.eks.cluster_name
  alb_arn_suffix               = local.alb_arn_suffix
  lambda_function_name         = module.lambda.lambda_function_name
  aurora_db_cluster_identifier = module.aurora.cluster_id

  monitoring_enable_sns_subscription = var.monitoring_enable_sns_subscription
  monitoring_notification_endpoint   = var.monitoring_notification_endpoint
  monitoring_notification_protocol   = var.monitoring_notification_protocol
}
